if(MSVC)
    add_compile_definitions(_CRT_SECURE_NO_WARNINGS)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        add_compile_options(/Zi /Od)
    else()
        add_compile_options(/O2)
    endif()
    if(MSVC_VERSION GREATER_EQUAL 1930)
        add_compile_options(/std:c++latest)
    else()
        message(WARNING "MSVC ${MSVC_VERSION} may not fully support C++23")
    endif()
endif()

if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        add_compile_options(-g -O0)
    else()
        add_compile_options(-O3 -DNDEBUG)
        if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 4.9)
            add_compile_options(-flto)
        endif()
    endif()
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 13.0)
        message(WARNING "GCC version ${CMAKE_CXX_COMPILER_VERSION} may not fully support C++23")
    endif()
endif()

if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        add_compile_options(-g -O0 -fsanitize=address,undefined)
        add_link_options(-fsanitize=address,undefined)
    else()
        add_compile_options(-O3 -DNDEBUG)
    endif()
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 17.0)
        message(WARNING "Clang version ${CMAKE_CXX_COMPILER_VERSION} may not fully support C++23")
    endif()
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_compile_definitions(MYSTL_DEBUG)
endif()

